### ISSUE TITLE
Island blueprint are not imported

### ISSUE THREAD

**Issue by xion87** [BentoBoxWorld/Converter#15]
I noticed the old player when they create end island or nether, they will generate a flying poo of blocks instead to generate the actually island, i think because the old imported island don't have the updated blueprint associated

**Comment by Poslovitch** [comment]
Could you please provide a screenshot of the "flying poo of blocks" ?

**Comment by xion87** [comment]
I think that is caused by player when falling in the void, it create  a block, the schematica is not generated

**Comment by tastybento** [comment]
If you want the nether island and end island auto-generated then you need to make that setting in the game mode's config.yml because the default setting is false now:

```
  # Create Nether or End islands if they are missing when a player goes through a portal.
  # Nether and End islands are usually pasted when a player makes their island, but if they are
  # missing for some reason, you can switch this on.
  # Note that bedrock removal glitches can exploit this option.
  create-missing-nether-end-islands: false
```
The safe-block must be coming from another plugin because we don't generate that. 

The reason why this was made default false was that players could remove the nether island bedrock block using a glitch and get multiple nether islands on teleporting. I'm not sure if this is still possible in 1.15.2. It's a vanilla glitch.
